.TH programName 1 "February 2023" "programName 0.1.0" "programName Manual"

.SH NAME
programName \- your program description here

.SH SYNOPSIS
.B programName
[\fB\-h\fR]
[\fB\-v\fR]
[\fIscript\fR]

.SH DESCRIPTION
.B programName
longer description here

.SH OPTIONS
.TP
.BR \-v ", " \-\-version
Prints the version of the programName interpreter.
.TP
.BR \-h ", " \-\-help
Prints this help message.
.TP
.BR \fIscript
Runs the programName script specified by \fIscript\fR.

.\" .SH SECTION 2
.\" Other secitions here

.SH AUTHOR
This manual page was written by the programName team

.SH INTERNET RESOURCES
programName website: \fBhttps://programName.com/\fR 
.br
programName docs: \fBhttps://programName.com/docs/\fR
.br
programName source code: \fBhttps://github.com/\fR

.\" example license
.SH LICENSING
MIT

Copyright (c) 2021

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.